### ISSUE TITLE
Roadmap to 0.2.0

### ISSUE THREAD

**Issue by disizali** [irandeno/interaction#15]
## api :
- [x] make `prefix, suffix, bold` global configurable

## types :
- [x] expose alphabetical type
- [x] expose checklist type

## core :
- [x] error handling

## examples
- [x] add examples for global configurable options

## fixes :
- [x] make numeric (and alphabetical) backslash work

## [x] Release 0.2.0

**Comment by disizali** [comment]
[v0.2.0](https://github.com/irandeno/interaction/releases/tag/0.2.0) Released!
