### ISSUE TITLE
Roadmap to 0.3.0

### ISSUE THREAD

**Issue by disizali** [irandeno/interaction#21]
## types :
- [ ] add password type
- [ ] add checklist's select all command available ( ctrl + a )

## api
- [ ] make screen cleaner ( after choice & checklist ) optional
